# Generated by Django 3.0.1 on 2020-04-28 23:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tvs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('enrolment', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('ptr', models.CharField(max_length=20)),
                ('ward', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100, null=True)),
                ('lat', models.CharField(max_length=10, null=True)),
                ('long', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('filename', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Only numbers are allowed', regex='^[0-9]+$')])),
                ('allocations', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('full_name', models.CharField(default='None', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, default='None', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('carrier', models.TextField(default='None', null=True)),
                ('experience', models.TextField(default='None', null=True)),
                ('skills', models.TextField(default='None', null=True)),
                ('why_volunteer', models.TextField()),
                ('status_update', models.IntegerField(default=0)),
                ('length', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(12)])),
                ('education', models.CharField(choices=[('None', 'None'), ('Certificate level', 'Certificate level'), ('Diploma level', 'Diploma level'), ('Degree level', 'Degree level'), ('Masters level', 'Masters level')], default='None', max_length=20, null=True)),
                ('school', models.CharField(blank=True, default='None', max_length=100)),
                ('ward', models.CharField(blank=True, default='Dar Es Salaam', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=10)),
                ('resume', models.FileField(blank=True, help_text='Please upload a PDF File', null=True, upload_to='resume/', validators=[tvs.models.validate_file_extension])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
