# Generated by Django 3.0.1 on 2020-04-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='school',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='school',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='ward',
        ),
    ]
