# Generated by Django 3.0.1 on 2020-04-28 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0002_auto_20200429_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='school',
            field=models.CharField(default=django.utils.timezone.now, max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='ward',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='school',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='ward',
            field=models.CharField(blank=True, default='Dar Es Salaam', max_length=150),
        ),
    ]
