# Generated by Django 3.0.1 on 2020-04-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0003_auto_20200429_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('canceling_reason', models.TextField()),
            ],
        ),
    ]
