# Generated by Django 3.0.1 on 2020-08-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0006_users_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='reason',
            field=models.TextField(default='Did not approved', null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status_update',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=20, null=True),
        ),
    ]
