# Generated by Django 3.1.4 on 2020-12-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0007_auto_20200805_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('name', models.CharField(default='none', max_length=20)),
                ('CouncilCode', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('RegionCode', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('WardCode', models.IntegerField(primary_key=True, serialize=False)),
                ('Council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvs.council')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvs.ward')),
            ],
        ),
        migrations.AddField(
            model_name='council',
            name='Regions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvs.regions'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='School1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school45', to='tvs.school'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='School2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school1', to='tvs.school'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='School3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school2', to='tvs.school'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='city1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='tvs.regions'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='city2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city1', to='tvs.regions'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='city3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city2', to='tvs.regions'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='council1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='council', to='tvs.council'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='council2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='council1', to='tvs.council'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='council3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='council2', to='tvs.council'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='ward1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='tvs.ward'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='ward2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward1', to='tvs.ward'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='ward3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward2', to='tvs.ward'),
        ),
    ]
