# Generated by Django 3.1.4 on 2020-12-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0008_auto_20201203_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=400, null=True)),
                ('council', models.CharField(max_length=400, null=True)),
                ('ward', models.CharField(max_length=400, null=True)),
                ('schoolname', models.CharField(max_length=400, null=True)),
                ('enrolment', models.CharField(max_length=400, null=True)),
                ('allteachers', models.CharField(max_length=400, null=True)),
                ('ptr', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='ward',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
