# Generated by Django 3.1.4 on 2020-12-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0009_auto_20201228_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='School1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='School2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='School3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='city1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='city2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='city3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='council1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='council2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='council3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='ward',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='ward1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='ward2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='ward3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
