# Generated by Django 3.1.7 on 2021-03-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0010_auto_20201228_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='ptr1',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='ptr2',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='ptr3',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
    ]
